#!/usr/bin/env bash
# install nginx

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
# check cat /etc/nginx/sites-available/default to get the pwd
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

