#!/usr/bin/env bash
# install nginx

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
# check cat /etc/nginx/sites-available/default to get the pwd
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
searchString="^\tlocation / {"
replaceString="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sudo sed -i "s@${searchString}@${replaceString}@" /etv/nginx/sites-available/default
sudo service nginx restart

