#!/usr/bin/env bash
# Prints strings 20 times using while loop and case
i=1
while [ $i -le 21 ]
do
    echo "$i"
    case $i in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
    esac
    let i=i+1
done
