#!/usr/bin/env bash
# Prints hours and minutes 12 hrs and 59 mins
hour=0
while [ $hour -le 12 ]
do
        minute=1
	echo "Hour: $hour"
	while [ $minute -le 59 ]
	do
		echo "$minute"
		let minute+=1
	done
	let hour+=1
done
